import type { Exercise } from '@workout/core';

export const BUILT_IN_EXERCISES: Exercise[] = [
  // Chest
  { id: 'ex_001', name: 'Barbell bench press', category: 'push', muscleGroup: 'chest', equipment: 'free weight' },
  { id: 'ex_002', name: 'Dumbbell bench press', category: 'push', muscleGroup: 'chest', equipment: 'free weight' },
  { id: 'ex_003', name: 'Incline barbell press', category: 'push', muscleGroup: 'chest', equipment: 'free weight' },
  { id: 'ex_004', name: 'Incline dumbbell press', category: 'push', muscleGroup: 'chest', equipment: 'free weight' },
  { id: 'ex_005', name: 'Decline barbell press', category: 'push', muscleGroup: 'chest', equipment: 'free weight' },
  { id: 'ex_006', name: 'Decline dumbbell press', category: 'push', muscleGroup: 'chest', equipment: 'free weight' },
  { id: 'ex_007', name: 'Machine chest press (flat)', category: 'push', muscleGroup: 'chest', equipment: 'machine' },
  { id: 'ex_008', name: 'Machine incline chest press', category: 'push', muscleGroup: 'chest', equipment: 'machine' },
  { id: 'ex_009', name: 'Machine decline chest press', category: 'push', muscleGroup: 'chest', equipment: 'machine' },
  { id: 'ex_010', name: 'Hammer Strength chest press', category: 'push', muscleGroup: 'chest', equipment: 'machine' },
  { id: 'ex_011', name: 'Smith machine bench press', category: 'push', muscleGroup: 'chest', equipment: 'machine' },
  { id: 'ex_012', name: 'Smith machine incline press', category: 'push', muscleGroup: 'chest', equipment: 'machine' },
  { id: 'ex_013', name: 'Cable chest fly (low to high)', category: 'push', muscleGroup: 'chest', equipment: 'cable' },
  { id: 'ex_014', name: 'Cable chest fly (high to low)', category: 'push', muscleGroup: 'chest', equipment: 'cable' },
  { id: 'ex_015', name: 'Cable chest fly (mid)', category: 'push', muscleGroup: 'chest', equipment: 'cable' },
  { id: 'ex_016', name: 'Dumbbell chest fly', category: 'push', muscleGroup: 'chest', equipment: 'free weight' },
  { id: 'ex_017', name: 'Incline dumbbell fly', category: 'push', muscleGroup: 'chest', equipment: 'free weight' },
  { id: 'ex_018', name: 'Pec deck machine', category: 'push', muscleGroup: 'chest', equipment: 'machine' },
  { id: 'ex_019', name: 'Push-up', category: 'push', muscleGroup: 'chest', equipment: 'bodyweight' },
  { id: 'ex_020', name: 'Incline push-up', category: 'push', muscleGroup: 'chest', equipment: 'bodyweight' },
  { id: 'ex_021', name: 'Decline push-up', category: 'push', muscleGroup: 'chest', equipment: 'bodyweight' },
  { id: 'ex_022', name: 'Wide-grip push-up', category: 'push', muscleGroup: 'chest', equipment: 'bodyweight' },
  { id: 'ex_023', name: 'Chest dip', category: 'push', muscleGroup: 'chest', equipment: 'bodyweight' },
  { id: 'ex_024', name: 'Landmine press', category: 'push', muscleGroup: 'chest', equipment: 'free weight' },
  { id: 'ex_025', name: 'Dumbbell pullover', category: 'push', muscleGroup: 'chest', equipment: 'free weight' },
  { id: 'ex_026', name: 'Cable pullover', category: 'push', muscleGroup: 'chest', equipment: 'cable' },
  { id: 'ex_027', name: 'Svend press', category: 'push', muscleGroup: 'chest', equipment: 'free weight' },
  // Back
  { id: 'ex_028', name: 'Barbell deadlift', category: 'pull', muscleGroup: 'back', equipment: 'free weight' },
  { id: 'ex_029', name: 'Romanian deadlift', category: 'pull', muscleGroup: 'back', equipment: 'free weight' },
  { id: 'ex_030', name: 'Sumo deadlift', category: 'pull', muscleGroup: 'back', equipment: 'free weight' },
  { id: 'ex_031', name: 'Pull-up', category: 'pull', muscleGroup: 'back', equipment: 'bodyweight' },
  { id: 'ex_032', name: 'Chin-up', category: 'pull', muscleGroup: 'back', equipment: 'bodyweight' },
  { id: 'ex_033', name: 'Wide-grip pull-up', category: 'pull', muscleGroup: 'back', equipment: 'bodyweight' },
  { id: 'ex_034', name: 'Neutral-grip pull-up', category: 'pull', muscleGroup: 'back', equipment: 'bodyweight' },
  { id: 'ex_035', name: 'Assisted pull-up machine', category: 'pull', muscleGroup: 'back', equipment: 'machine' },
  { id: 'ex_036', name: 'Barbell row (overhand)', category: 'pull', muscleGroup: 'back', equipment: 'free weight' },
  { id: 'ex_037', name: 'Barbell row (underhand)', category: 'pull', muscleGroup: 'back', equipment: 'free weight' },
  { id: 'ex_038', name: 'Dumbbell row', category: 'pull', muscleGroup: 'back', equipment: 'free weight' },
  { id: 'ex_039', name: 'Meadows row', category: 'pull', muscleGroup: 'back', equipment: 'free weight' },
  { id: 'ex_040', name: 'Pendlay row', category: 'pull', muscleGroup: 'back', equipment: 'free weight' },
  { id: 'ex_041', name: 'T-bar row (landmine)', category: 'pull', muscleGroup: 'back', equipment: 'free weight' },
  { id: 'ex_042', name: 'T-bar row machine', category: 'pull', muscleGroup: 'back', equipment: 'machine' },
  { id: 'ex_043', name: 'Machine seated row', category: 'pull', muscleGroup: 'back', equipment: 'machine' },
  { id: 'ex_044', name: 'Machine chest-supported row', category: 'pull', muscleGroup: 'back', equipment: 'machine' },
  { id: 'ex_045', name: 'Hammer Strength high row', category: 'pull', muscleGroup: 'back', equipment: 'machine' },
  { id: 'ex_046', name: 'Hammer Strength low row', category: 'pull', muscleGroup: 'back', equipment: 'machine' },
  { id: 'ex_047', name: 'Lat pulldown (wide grip)', category: 'pull', muscleGroup: 'back', equipment: 'cable' },
  { id: 'ex_048', name: 'Lat pulldown (close grip)', category: 'pull', muscleGroup: 'back', equipment: 'cable' },
  { id: 'ex_049', name: 'Lat pulldown (neutral grip)', category: 'pull', muscleGroup: 'back', equipment: 'cable' },
  { id: 'ex_050', name: 'Lat pulldown (underhand)', category: 'pull', muscleGroup: 'back', equipment: 'cable' },
  { id: 'ex_051', name: 'Cable seated row (wide grip)', category: 'pull', muscleGroup: 'back', equipment: 'cable' },
  { id: 'ex_052', name: 'Cable seated row (close grip)', category: 'pull', muscleGroup: 'back', equipment: 'cable' },
  { id: 'ex_053', name: 'Single-arm cable row', category: 'pull', muscleGroup: 'back', equipment: 'cable' },
  { id: 'ex_054', name: 'Straight-arm pulldown', category: 'pull', muscleGroup: 'back', equipment: 'cable' },
  { id: 'ex_055', name: 'Face pull', category: 'pull', muscleGroup: 'back', equipment: 'cable' },
  { id: 'ex_056', name: 'Rack pull', category: 'pull', muscleGroup: 'back', equipment: 'free weight' },
  { id: 'ex_057', name: 'Good morning', category: 'pull', muscleGroup: 'back', equipment: 'free weight' },
  { id: 'ex_058', name: 'Hyperextension (back extension)', category: 'pull', muscleGroup: 'back', equipment: 'bodyweight' },
  { id: 'ex_059', name: 'Reverse hyperextension', category: 'pull', muscleGroup: 'back', equipment: 'machine' },
  { id: 'ex_060', name: 'Machine back extension', category: 'pull', muscleGroup: 'back', equipment: 'machine' },
  { id: 'ex_061', name: 'Inverted row', category: 'pull', muscleGroup: 'back', equipment: 'bodyweight' },
  { id: 'ex_062', name: 'Renegade row', category: 'pull', muscleGroup: 'back', equipment: 'free weight' },
  // Shoulders
  { id: 'ex_063', name: 'Barbell overhead press', category: 'push', muscleGroup: 'shoulders', equipment: 'free weight' },
  { id: 'ex_064', name: 'Seated barbell press', category: 'push', muscleGroup: 'shoulders', equipment: 'free weight' },
  { id: 'ex_065', name: 'Dumbbell shoulder press', category: 'push', muscleGroup: 'shoulders', equipment: 'free weight' },
  { id: 'ex_066', name: 'Seated dumbbell press', category: 'push', muscleGroup: 'shoulders', equipment: 'free weight' },
  { id: 'ex_067', name: 'Arnold press', category: 'push', muscleGroup: 'shoulders', equipment: 'free weight' },
  { id: 'ex_068', name: 'Machine shoulder press', category: 'push', muscleGroup: 'shoulders', equipment: 'machine' },
  { id: 'ex_069', name: 'Smith machine overhead press', category: 'push', muscleGroup: 'shoulders', equipment: 'machine' },
  { id: 'ex_070', name: 'Hammer Strength shoulder press', category: 'push', muscleGroup: 'shoulders', equipment: 'machine' },
  { id: 'ex_071', name: 'Lateral raise (dumbbell)', category: 'push', muscleGroup: 'shoulders', equipment: 'free weight' },
  { id: 'ex_072', name: 'Cable lateral raise', category: 'push', muscleGroup: 'shoulders', equipment: 'cable' },
  { id: 'ex_073', name: 'Machine lateral raise', category: 'push', muscleGroup: 'shoulders', equipment: 'machine' },
  { id: 'ex_074', name: 'Leaning cable lateral raise', category: 'push', muscleGroup: 'shoulders', equipment: 'cable' },
  { id: 'ex_075', name: 'Front raise (dumbbell)', category: 'push', muscleGroup: 'shoulders', equipment: 'free weight' },
  { id: 'ex_076', name: 'Front raise (barbell)', category: 'push', muscleGroup: 'shoulders', equipment: 'free weight' },
  { id: 'ex_077', name: 'Cable front raise', category: 'push', muscleGroup: 'shoulders', equipment: 'cable' },
  { id: 'ex_078', name: 'Rear delt fly (dumbbell)', category: 'push', muscleGroup: 'shoulders', equipment: 'free weight' },
  { id: 'ex_079', name: 'Rear delt fly (machine)', category: 'push', muscleGroup: 'shoulders', equipment: 'machine' },
  { id: 'ex_080', name: 'Reverse pec deck', category: 'push', muscleGroup: 'shoulders', equipment: 'machine' },
  { id: 'ex_081', name: 'Cable rear delt fly', category: 'push', muscleGroup: 'shoulders', equipment: 'cable' },
  { id: 'ex_082', name: 'Upright row (barbell)', category: 'push', muscleGroup: 'shoulders', equipment: 'free weight' },
  { id: 'ex_083', name: 'Upright row (cable)', category: 'push', muscleGroup: 'shoulders', equipment: 'cable' },
  { id: 'ex_084', name: 'Landmine lateral raise', category: 'push', muscleGroup: 'shoulders', equipment: 'free weight' },
  { id: 'ex_085', name: 'Landmine press', category: 'push', muscleGroup: 'shoulders', equipment: 'free weight' },
  { id: 'ex_086', name: 'Shrug (barbell)', category: 'push', muscleGroup: 'shoulders', equipment: 'free weight' },
  { id: 'ex_087', name: 'Shrug (dumbbell)', category: 'push', muscleGroup: 'shoulders', equipment: 'free weight' },
  { id: 'ex_088', name: 'Shrug (machine)', category: 'push', muscleGroup: 'shoulders', equipment: 'machine' },
  { id: 'ex_089', name: 'Shrug (cable)', category: 'push', muscleGroup: 'shoulders', equipment: 'cable' },
  { id: 'ex_090', name: 'Pike push-up', category: 'push', muscleGroup: 'shoulders', equipment: 'bodyweight' },
  { id: 'ex_091', name: 'Handstand push-up', category: 'push', muscleGroup: 'shoulders', equipment: 'bodyweight' },
  // Biceps
  { id: 'ex_092', name: 'Barbell curl', category: 'pull', muscleGroup: 'biceps', equipment: 'free weight' },
  { id: 'ex_093', name: 'EZ-bar curl', category: 'pull', muscleGroup: 'biceps', equipment: 'free weight' },
  { id: 'ex_094', name: 'Dumbbell curl', category: 'pull', muscleGroup: 'biceps', equipment: 'free weight' },
  { id: 'ex_095', name: 'Alternating dumbbell curl', category: 'pull', muscleGroup: 'biceps', equipment: 'free weight' },
  { id: 'ex_096', name: 'Hammer curl', category: 'pull', muscleGroup: 'biceps', equipment: 'free weight' },
  { id: 'ex_097', name: 'Cross-body hammer curl', category: 'pull', muscleGroup: 'biceps', equipment: 'free weight' },
  { id: 'ex_098', name: 'Incline dumbbell curl', category: 'pull', muscleGroup: 'biceps', equipment: 'free weight' },
  { id: 'ex_099', name: 'Concentration curl', category: 'pull', muscleGroup: 'biceps', equipment: 'free weight' },
  { id: 'ex_100', name: 'Spider curl', category: 'pull', muscleGroup: 'biceps', equipment: 'free weight' },
  { id: 'ex_101', name: 'Preacher curl (barbell)', category: 'pull', muscleGroup: 'biceps', equipment: 'free weight' },
  { id: 'ex_102', name: 'Preacher curl (dumbbell)', category: 'pull', muscleGroup: 'biceps', equipment: 'free weight' },
  { id: 'ex_103', name: 'Preacher curl machine', category: 'pull', muscleGroup: 'biceps', equipment: 'machine' },
  { id: 'ex_104', name: 'Cable curl (straight bar)', category: 'pull', muscleGroup: 'biceps', equipment: 'cable' },
  { id: 'ex_105', name: 'Cable curl (EZ bar)', category: 'pull', muscleGroup: 'biceps', equipment: 'cable' },
  { id: 'ex_106', name: 'Single-arm cable curl', category: 'pull', muscleGroup: 'biceps', equipment: 'cable' },
  { id: 'ex_107', name: 'High cable curl', category: 'pull', muscleGroup: 'biceps', equipment: 'cable' },
  { id: 'ex_108', name: 'Machine bicep curl', category: 'pull', muscleGroup: 'biceps', equipment: 'machine' },
  { id: 'ex_109', name: 'Zottman curl', category: 'pull', muscleGroup: 'biceps', equipment: 'free weight' },
  { id: 'ex_110', name: 'Reverse curl', category: 'pull', muscleGroup: 'biceps', equipment: 'free weight' },
  { id: 'ex_111', name: '21s', category: 'pull', muscleGroup: 'biceps', equipment: 'free weight' },
  // Triceps
  { id: 'ex_112', name: 'Tricep pushdown (straight bar)', category: 'push', muscleGroup: 'triceps', equipment: 'cable' },
  { id: 'ex_113', name: 'Tricep pushdown (rope)', category: 'push', muscleGroup: 'triceps', equipment: 'cable' },
  { id: 'ex_114', name: 'Tricep pushdown (V-bar)', category: 'push', muscleGroup: 'triceps', equipment: 'cable' },
  { id: 'ex_115', name: 'Overhead tricep extension (cable)', category: 'push', muscleGroup: 'triceps', equipment: 'cable' },
  { id: 'ex_116', name: 'Overhead tricep extension (dumbbell)', category: 'push', muscleGroup: 'triceps', equipment: 'free weight' },
  { id: 'ex_117', name: 'Overhead tricep extension (EZ-bar)', category: 'push', muscleGroup: 'triceps', equipment: 'free weight' },
  { id: 'ex_118', name: 'Skull crusher (barbell)', category: 'push', muscleGroup: 'triceps', equipment: 'free weight' },
  { id: 'ex_119', name: 'Skull crusher (EZ-bar)', category: 'push', muscleGroup: 'triceps', equipment: 'free weight' },
  { id: 'ex_120', name: 'Skull crusher (dumbbell)', category: 'push', muscleGroup: 'triceps', equipment: 'free weight' },
  { id: 'ex_121', name: 'Close-grip bench press', category: 'push', muscleGroup: 'triceps', equipment: 'free weight' },
  { id: 'ex_122', name: 'Tricep dip', category: 'push', muscleGroup: 'triceps', equipment: 'bodyweight' },
  { id: 'ex_123', name: 'Bench dip', category: 'push', muscleGroup: 'triceps', equipment: 'bodyweight' },
  { id: 'ex_124', name: 'Diamond push-up', category: 'push', muscleGroup: 'triceps', equipment: 'bodyweight' },
  { id: 'ex_125', name: 'Machine tricep press', category: 'push', muscleGroup: 'triceps', equipment: 'machine' },
  { id: 'ex_126', name: 'Machine tricep dip', category: 'push', muscleGroup: 'triceps', equipment: 'machine' },
  { id: 'ex_127', name: 'Tricep kickback (dumbbell)', category: 'push', muscleGroup: 'triceps', equipment: 'free weight' },
  { id: 'ex_128', name: 'Tricep kickback (cable)', category: 'push', muscleGroup: 'triceps', equipment: 'cable' },
  { id: 'ex_129', name: 'Tate press', category: 'push', muscleGroup: 'triceps', equipment: 'free weight' },
  { id: 'ex_130', name: 'JM press', category: 'push', muscleGroup: 'triceps', equipment: 'free weight' },
  // Quads
  { id: 'ex_131', name: 'Barbell back squat', category: 'legs', muscleGroup: 'quads', equipment: 'free weight' },
  { id: 'ex_132', name: 'Barbell front squat', category: 'legs', muscleGroup: 'quads', equipment: 'free weight' },
  { id: 'ex_133', name: 'Goblet squat', category: 'legs', muscleGroup: 'quads', equipment: 'free weight' },
  { id: 'ex_134', name: 'Sumo squat', category: 'legs', muscleGroup: 'quads', equipment: 'free weight' },
  { id: 'ex_135', name: 'Smith machine squat', category: 'legs', muscleGroup: 'quads', equipment: 'machine' },
  { id: 'ex_136', name: 'Leg press (standard)', category: 'legs', muscleGroup: 'quads', equipment: 'machine' },
  { id: 'ex_137', name: 'Leg press (narrow stance)', category: 'legs', muscleGroup: 'quads', equipment: 'machine' },
  { id: 'ex_138', name: 'Leg press (wide stance)', category: 'legs', muscleGroup: 'quads', equipment: 'machine' },
  { id: 'ex_139', name: 'Hack squat machine', category: 'legs', muscleGroup: 'quads', equipment: 'machine' },
  { id: 'ex_140', name: 'V-squat machine', category: 'legs', muscleGroup: 'quads', equipment: 'machine' },
  { id: 'ex_141', name: 'Leg extension machine', category: 'legs', muscleGroup: 'quads', equipment: 'machine' },
  { id: 'ex_142', name: 'Bulgarian split squat', category: 'legs', muscleGroup: 'quads', equipment: 'free weight' },
  { id: 'ex_143', name: 'Lunge (dumbbell)', category: 'legs', muscleGroup: 'quads', equipment: 'free weight' },
  { id: 'ex_144', name: 'Lunge (barbell)', category: 'legs', muscleGroup: 'quads', equipment: 'free weight' },
  { id: 'ex_145', name: 'Walking lunge', category: 'legs', muscleGroup: 'quads', equipment: 'free weight' },
  { id: 'ex_146', name: 'Reverse lunge', category: 'legs', muscleGroup: 'quads', equipment: 'bodyweight' },
  { id: 'ex_147', name: 'Step-up', category: 'legs', muscleGroup: 'quads', equipment: 'free weight' },
  { id: 'ex_148', name: 'Sissy squat', category: 'legs', muscleGroup: 'quads', equipment: 'bodyweight' },
  { id: 'ex_149', name: 'Landmine squat', category: 'legs', muscleGroup: 'quads', equipment: 'free weight' },
  { id: 'ex_150', name: 'Cyclist squat', category: 'legs', muscleGroup: 'quads', equipment: 'free weight' },
  { id: 'ex_151', name: 'Box squat', category: 'legs', muscleGroup: 'quads', equipment: 'free weight' },
  { id: 'ex_152', name: 'Wall sit', category: 'legs', muscleGroup: 'quads', equipment: 'bodyweight' },
  // Hamstrings
  { id: 'ex_153', name: 'Romanian deadlift (barbell)', category: 'legs', muscleGroup: 'hamstrings', equipment: 'free weight' },
  { id: 'ex_154', name: 'Romanian deadlift (dumbbell)', category: 'legs', muscleGroup: 'hamstrings', equipment: 'free weight' },
  { id: 'ex_155', name: 'Single-leg RDL', category: 'legs', muscleGroup: 'hamstrings', equipment: 'free weight' },
  { id: 'ex_156', name: 'Stiff-leg deadlift', category: 'legs', muscleGroup: 'hamstrings', equipment: 'free weight' },
  { id: 'ex_157', name: 'Lying leg curl machine', category: 'legs', muscleGroup: 'hamstrings', equipment: 'machine' },
  { id: 'ex_158', name: 'Seated leg curl machine', category: 'legs', muscleGroup: 'hamstrings', equipment: 'machine' },
  { id: 'ex_159', name: 'Standing leg curl machine', category: 'legs', muscleGroup: 'hamstrings', equipment: 'machine' },
  { id: 'ex_160', name: 'Nordic curl', category: 'legs', muscleGroup: 'hamstrings', equipment: 'bodyweight' },
  { id: 'ex_161', name: 'Glute-ham raise', category: 'legs', muscleGroup: 'hamstrings', equipment: 'machine' },
  { id: 'ex_162', name: 'Cable leg curl', category: 'legs', muscleGroup: 'hamstrings', equipment: 'cable' },
  { id: 'ex_163', name: 'Good morning', category: 'legs', muscleGroup: 'hamstrings', equipment: 'free weight' },
  { id: 'ex_164', name: 'Swiss ball leg curl', category: 'legs', muscleGroup: 'hamstrings', equipment: 'bodyweight' },
  // Glutes
  { id: 'ex_165', name: 'Hip thrust (barbell)', category: 'legs', muscleGroup: 'glutes', equipment: 'free weight' },
  { id: 'ex_166', name: 'Hip thrust machine', category: 'legs', muscleGroup: 'glutes', equipment: 'machine' },
  { id: 'ex_167', name: 'Cable pull-through', category: 'legs', muscleGroup: 'glutes', equipment: 'cable' },
  { id: 'ex_168', name: 'Glute bridge', category: 'legs', muscleGroup: 'glutes', equipment: 'bodyweight' },
  { id: 'ex_169', name: 'Single-leg glute bridge', category: 'legs', muscleGroup: 'glutes', equipment: 'bodyweight' },
  { id: 'ex_170', name: 'Romanian deadlift', category: 'legs', muscleGroup: 'glutes', equipment: 'free weight' },
  { id: 'ex_171', name: 'Sumo deadlift', category: 'legs', muscleGroup: 'glutes', equipment: 'free weight' },
  { id: 'ex_172', name: 'Cable kickback', category: 'legs', muscleGroup: 'glutes', equipment: 'cable' },
  { id: 'ex_173', name: 'Machine kickback', category: 'legs', muscleGroup: 'glutes', equipment: 'machine' },
  { id: 'ex_174', name: 'Abductor machine', category: 'legs', muscleGroup: 'glutes', equipment: 'machine' },
  { id: 'ex_175', name: 'Adductor machine', category: 'legs', muscleGroup: 'glutes', equipment: 'machine' },
  { id: 'ex_176', name: 'Clamshell', category: 'legs', muscleGroup: 'glutes', equipment: 'bodyweight' },
  { id: 'ex_177', name: 'Banded squat walk', category: 'legs', muscleGroup: 'glutes', equipment: 'bodyweight' },
  { id: 'ex_178', name: 'Donkey kick', category: 'legs', muscleGroup: 'glutes', equipment: 'bodyweight' },
  { id: 'ex_179', name: 'Fire hydrant', category: 'legs', muscleGroup: 'glutes', equipment: 'bodyweight' },
  { id: 'ex_180', name: 'Step-up', category: 'legs', muscleGroup: 'glutes', equipment: 'free weight' },
  { id: 'ex_181', name: 'Bulgarian split squat', category: 'legs', muscleGroup: 'glutes', equipment: 'free weight' },
  // Calves
  { id: 'ex_182', name: 'Standing calf raise (machine)', category: 'legs', muscleGroup: 'calves', equipment: 'machine' },
  { id: 'ex_183', name: 'Seated calf raise (machine)', category: 'legs', muscleGroup: 'calves', equipment: 'machine' },
  { id: 'ex_184', name: 'Leg press calf raise', category: 'legs', muscleGroup: 'calves', equipment: 'machine' },
  { id: 'ex_185', name: 'Single-leg calf raise (bodyweight)', category: 'legs', muscleGroup: 'calves', equipment: 'bodyweight' },
  { id: 'ex_186', name: 'Calf raise (barbell)', category: 'legs', muscleGroup: 'calves', equipment: 'free weight' },
  { id: 'ex_187', name: 'Calf raise (dumbbell)', category: 'legs', muscleGroup: 'calves', equipment: 'free weight' },
  { id: 'ex_188', name: 'Smith machine calf raise', category: 'legs', muscleGroup: 'calves', equipment: 'machine' },
  { id: 'ex_189', name: 'Donkey calf raise', category: 'legs', muscleGroup: 'calves', equipment: 'machine' },
  { id: 'ex_190', name: 'Tibialis raise', category: 'legs', muscleGroup: 'calves', equipment: 'bodyweight' },
  // Core
  { id: 'ex_191', name: 'Crunch', category: 'core', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex_192', name: 'Cable crunch', category: 'core', muscleGroup: 'core', equipment: 'cable' },
  { id: 'ex_193', name: 'Machine crunch', category: 'core', muscleGroup: 'core', equipment: 'machine' },
  { id: 'ex_194', name: 'Decline crunch', category: 'core', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex_195', name: 'Bicycle crunch', category: 'core', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex_196', name: 'Reverse crunch', category: 'core', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex_197', name: 'Leg raise (lying)', category: 'core', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex_198', name: 'Hanging leg raise', category: 'core', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex_199', name: 'Hanging knee raise', category: 'core', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex_200', name: 'Toes to bar', category: 'core', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex_201', name: 'Plank', category: 'core', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex_202', name: 'Side plank', category: 'core', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex_203', name: 'Plank with shoulder tap', category: 'core', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex_204', name: 'Russian twist', category: 'core', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex_205', name: 'Ab wheel rollout', category: 'core', muscleGroup: 'core', equipment: 'free weight' },
  { id: 'ex_206', name: 'Cable woodchop', category: 'core', muscleGroup: 'core', equipment: 'cable' },
  { id: 'ex_207', name: 'Pallof press', category: 'core', muscleGroup: 'core', equipment: 'cable' },
  { id: 'ex_208', name: 'Dead bug', category: 'core', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex_209', name: 'V-up', category: 'core', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex_210', name: 'Sit-up', category: 'core', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex_211', name: 'Dragon flag', category: 'core', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex_212', name: 'L-sit', category: 'core', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex_213', name: 'Hollow body hold', category: 'core', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex_214', name: 'Suitcase carry', category: 'core', muscleGroup: 'core', equipment: 'free weight' },
  { id: 'ex_215', name: 'Landmine rotation', category: 'core', muscleGroup: 'core', equipment: 'free weight' },
  { id: 'ex_216', name: 'Decline sit-up', category: 'core', muscleGroup: 'core', equipment: 'bodyweight' },
  // Forearms
  { id: 'ex_217', name: 'Wrist curl (dumbbell)', category: 'pull', muscleGroup: 'forearms', equipment: 'free weight' },
  { id: 'ex_218', name: 'Wrist curl (barbell)', category: 'pull', muscleGroup: 'forearms', equipment: 'free weight' },
  { id: 'ex_219', name: 'Reverse wrist curl', category: 'pull', muscleGroup: 'forearms', equipment: 'free weight' },
  { id: 'ex_220', name: 'Reverse curl', category: 'pull', muscleGroup: 'forearms', equipment: 'free weight' },
  { id: 'ex_221', name: 'Hammer curl', category: 'pull', muscleGroup: 'forearms', equipment: 'free weight' },
  { id: 'ex_222', name: 'Plate pinch', category: 'pull', muscleGroup: 'forearms', equipment: 'free weight' },
  { id: 'ex_223', name: "Farmer's carry", category: 'pull', muscleGroup: 'forearms', equipment: 'free weight' },
  { id: 'ex_224', name: 'Cable wrist curl', category: 'pull', muscleGroup: 'forearms', equipment: 'cable' },
  { id: 'ex_225', name: 'Wrist roller', category: 'pull', muscleGroup: 'forearms', equipment: 'free weight' },
  { id: 'ex_226', name: 'Dead hang', category: 'pull', muscleGroup: 'forearms', equipment: 'bodyweight' },
  { id: 'ex_227', name: 'Towel pull-up', category: 'pull', muscleGroup: 'forearms', equipment: 'bodyweight' },
  // Full Body
  { id: 'ex_228', name: 'Power clean', category: 'cardio', muscleGroup: 'full_body', equipment: 'free weight' },
  { id: 'ex_229', name: 'Clean and jerk', category: 'cardio', muscleGroup: 'full_body', equipment: 'free weight' },
  { id: 'ex_230', name: 'Snatch', category: 'cardio', muscleGroup: 'full_body', equipment: 'free weight' },
  { id: 'ex_231', name: 'Hang clean', category: 'cardio', muscleGroup: 'full_body', equipment: 'free weight' },
  { id: 'ex_232', name: 'Thruster', category: 'cardio', muscleGroup: 'full_body', equipment: 'free weight' },
  { id: 'ex_233', name: 'Kettlebell swing', category: 'cardio', muscleGroup: 'full_body', equipment: 'free weight' },
  { id: 'ex_234', name: 'Kettlebell clean', category: 'cardio', muscleGroup: 'full_body', equipment: 'free weight' },
  { id: 'ex_235', name: 'Kettlebell snatch', category: 'cardio', muscleGroup: 'full_body', equipment: 'free weight' },
  { id: 'ex_236', name: 'Turkish get-up', category: 'cardio', muscleGroup: 'full_body', equipment: 'free weight' },
  { id: 'ex_237', name: 'Box jump', category: 'cardio', muscleGroup: 'full_body', equipment: 'bodyweight' },
  { id: 'ex_238', name: 'Broad jump', category: 'cardio', muscleGroup: 'full_body', equipment: 'bodyweight' },
  { id: 'ex_239', name: 'Burpee', category: 'cardio', muscleGroup: 'full_body', equipment: 'bodyweight' },
  { id: 'ex_240', name: 'Battle ropes', category: 'cardio', muscleGroup: 'full_body', equipment: 'machine' },
  { id: 'ex_241', name: 'Sled push', category: 'cardio', muscleGroup: 'full_body', equipment: 'machine' },
  { id: 'ex_242', name: 'Sled pull', category: 'cardio', muscleGroup: 'full_body', equipment: 'machine' },
  { id: 'ex_243', name: "Farmer's carry", category: 'cardio', muscleGroup: 'full_body', equipment: 'free weight' },
  { id: 'ex_244', name: 'Sandbag carry', category: 'cardio', muscleGroup: 'full_body', equipment: 'free weight' },
  { id: 'ex_245', name: 'Tire flip', category: 'cardio', muscleGroup: 'full_body', equipment: 'free weight' },
  { id: 'ex_246', name: 'Medicine ball slam', category: 'cardio', muscleGroup: 'full_body', equipment: 'free weight' },
  { id: 'ex_247', name: 'Medicine ball throw', category: 'cardio', muscleGroup: 'full_body', equipment: 'free weight' },
  { id: 'ex_248', name: 'Rowing machine', category: 'cardio', muscleGroup: 'full_body', equipment: 'machine' },
  { id: 'ex_249', name: 'Ski erg', category: 'cardio', muscleGroup: 'full_body', equipment: 'machine' },
  { id: 'ex_250', name: 'Assault bike', category: 'cardio', muscleGroup: 'full_body', equipment: 'machine' },
];
